### ISSUE TITLE
Exception while installing the "uAAL-Basic.Coordinator" feature

### ISSUE THREAD

**Issue by steveStavros** [universAAL/platform#12]
Hi all,
I am trying to set uAAL in a Raspeberry pi 3 device. I downloaded the karaf distribution of uAAL ( https://github.com/universAAL/distro.karaf) and then I used the starting guide (https://github.com/universAAL/platform/wiki/DG-Quick-setup-and-start-guide) and tried to install the "uAAL-Basic.Coordinator" feature, as it is recommended, but I get the following error:

Error executing command: Can't install feature uAAL-Basic.Coordinator/0.0.0:
Could not start bundle mvn:org.universAAL.ui/ui.resource.server/3.4.1-SNAPSHOT in feature(s) uAAL-UI.resource.server-3.4.1-SNAPSHOT: Unresolved constraint in bundle ui.resource.server [135]: Unable to resolve 135.0: missing requirement [135.0] osgi.wiring.package; (&(osgi.wiring.package=org.universAAL.middleware.container.osgi.util)(version>=3.4.0)(!(version>=4.0.0)))

**Comment by Alfiva** [comment]
I think it may be related to some refactoring of core packages, but someone else could confirm it.
Anyway, I see multiple possible solutions or workarounds:
a) If all the bundles did manage to get installed (unlikely), and it's only that bundle that fails to "start", and if you are not going to deal with the UI bus, then I guess you can continue as usual.
b) Try with last release version 3.4.0: In karaf.distros repo, use the tag branch 3.4.0.
c) Try with last release version 3.4.0: In the karaf/etc folder you already have, open org.apache.karaf.features.cfg file and find the reference to uAAL feature with version 3.4.1-SNAPSHOT. Change it to 3.4.0 (You may have to remove the whole karaf folder and start from scratch before doing this).

**Comment by amedranogil** [comment]
Original message included an exception:
```
Exception in thread "Thread-1282" java.lang.NullPointerException
	at java.io.Writer.write(Writer.java:157)
	at org.universAAL.context.che.Hub.createOWLFile(Hub.java:225)
	at org.universAAL.context.che.Hub.createOWLFiles(Hub.java:183)
	at org.universAAL.context.che.Hub.start(Hub.java:148)
	at org.universAAL.context.che.osgi.Activator$1.run(Activator.java:86)
ERROR: Bundle ctxt.che [101] Error stopping bundle. (java.lang.NullPointerException)
java.lang.NullPointerException
	at org.universAAL.context.che.Hub.stop(Hub.java:244)
	at org.universAAL.context.che.osgi.Activator.stop(Activator.java:98)
       ...
```

I guess either the pocess does not have read/write access; or that there is some problem with some ontology which produces "null" serialization.

**Comment by Alfiva** [comment]
That is confusing. The first message referenced the UI Resource server because of missing org.universAAL.middleware.container.osgi.util package, but this exception you pasted is because of CHE. Has tehre been some mix up?
Anyway, if that CHE-related exception is also present at the situation reported by @steveStavros I agree with @amedranogil . If you do not actually need the CHE, but got installed by default, simply uninstall the bundle, or stop it, and just ignore this.
If you need the CHE, first make sure it is properly configured for running in RPi environment by modifying accordingly its properties file in etc/ctxt.che/CHe.properties. See https://github.com/universAAL/context/wiki/Context-History-Entrepot#Configuration for reference.
As pointed out, this may be caused by some ontology that produces null serialization. Which ontologies are you using? are you using any custom one? How do you install them?

**Comment by steveStavros** [comment]
The exception thrown is not related to the running environment. I just tried the same procedure in windows and I got the same result.
We need to use uAAL for a new project and probably create our own apps, so I tried to follow step by step the instructions provided (https://github.com/universAAL/platform/wiki/DG-Quick-setup-and-start-guide). I do not know yet if we are going to use CHE and I haven't installed any ontologies. I just downloaded the karaf distribution and after I ran it for the first time I tried to experiment and install the uAAL-Basic.Coordinator feature as it is recommended at step 8 (I did not make any other installations). 

I will keep it  as it is for now. In case there is a need for installing this feature I will try one of the workarounds of @Alfiva 

Thanks!!

**Comment by amedranogil** [comment]
for the time being install just the _uAAL-MW_ feature and if you need more features go from there.
