### ISSUE TITLE
nostart feature of uaal-maven-plugin

### ISSUE THREAD

**Issue by amedranogil** [universAAL/platform#19]
_Originally Opened: @jacekpsiuk (2012-09-16 00:00:00_)
_Originally Closed: 2012-09-18 00:00:00_

There was a request (from Thomas Fuxreiter) of adding a way of configuring the uaal-maven-plugin to add a @nostart parameter to certain bundles during the composite file generation, thus disabling their automatic start in a test environment.

There request included the @nostart parameter and/or a @&lt;number of startlevel&gt; to control bundles' start strategy.

--

From: _this issue has been automatically imported from our old issue tracker_

**Comment by amedranogil** [comment]
_Original author: @cstockloew (2012-09-17 20:33:26)_

With the new version I was not able to MavenInstall the middleware. I have now re-deployed the old version. Please have a look at it and test your locally installed new version with the existing repos.

**Comment by amedranogil** [comment]
_Original author: @cstockloew (2012-09-18 02:36:04)_

The error message during RunAs-MavenInstall on mw.pom:

Creating MAIN composite file - output generated in target/artifact.composite and target/artifact.deps


[INFO] Dependency tree for artifact: org.universAAL.middleware:mw.container.xfaces.osgi:jar:1.2.1-SNAPSHOT
org.universAAL.middleware:mw.container.xfaces.osgi:jar:1.2.1-SNAPSHOT
   org.universAAL.middleware:mw.container.xfaces.core:jar:1.2.1-SNAPSHOT:compile

[ERROR] 
java.lang.NullPointerException
	at org.universAAL.maven.LaunchOrderDependencyNodeVisitor.addNode(LaunchOrderDependencyNodeVisitor.java:265)
	at org.universAAL.maven.LaunchOrderDependencyNodeVisitor.endVisit(LaunchOrderDependencyNodeVisitor.java:378)
	at org.apache.maven.shared.dependency.tree.DependencyNode.accept(DependencyNode.java:317)
	at org.universAAL.maven.treebuilder.ExecutionListCreator.processTreeIntoFlatList(ExecutionListCreator.java:232)
	at org.universAAL.maven.treebuilder.ExecutionListCreator.createArtifactExecutionList(ExecutionListCreator.java:335)
	at org.universAAL.maven.UaalCompositeMojo.execute(UaalCompositeMojo.java:215)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:107)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:319)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:534)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)

**Comment by amedranogil** [comment]
_Original author: @jacekpsiuk (2012-09-18 11:26:03)_

fixed! committed and deployed.

**Comment by amedranogil** [comment]
issue cloed on 2012-09-18 00:00:00
