### ISSUE TITLE
required testing bundle is not automatically installed

### ISSUE THREAD

**Issue by amedranogil** [universAAL/platform#28]
_Originally Opened: @amedranogil (2014-05-08 11:41:39_)
_Originally Closed: 2014-05-08 12:51:21_

When building an artifact with Integration tests with a clean Maven local repo, a required bundle is not automatically installed.

It is suggested to add this bundle as a forced dependency in top level POMs with scope test, so it gets automatically installed at least the first time.

testComposite(org.universAAL.ontology.test.ArtifactIT)  Time elapsed: 0.49 sec  &lt;&lt;&lt; ERROR!
java.io.FileNotFoundException: C:\Users\amedrano\.m2\repository\org\slf4j\com.springsource.slf4j.api\1.5.0\com.springsource.slf4j.api-1.5.0.jar (El sistema no puede encontrar la ruta especificada)
	at java.io.FileInputStream.open(Native Method)
	at java.io.FileInputStream.&lt;init&gt;(Unknown Source)
	at org.springframework.core.io.FileSystemResource.getInputStream(FileSystemResource.java:108)
	at org.springframework.osgi.test.AbstractOsgiTests.installBundle(AbstractOsgiTests.java:323)
	at org.springframework.osgi.test.AbstractOsgiTests.startup(AbstractOsgiTests.java:253)
	at org.springframework.osgi.test.AbstractOsgiTests.prepareTestExecution(AbstractOsgiTests.java:374)
	at org.springframework.osgi.test.AbstractOsgiTests.runBare(AbstractOsgiTests.java:203)
	at org.springframework.osgi.test.AbstractOsgiTests$1.protect(AbstractOsgiTests.java:184)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at org.springframework.osgi.test.AbstractOsgiTests.run(AbstractOsgiTests.java:181)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.apache.maven.surefire.junit.JUnitTestSet.execute(JUnitTestSet.java:95)
	at org.apache.maven.surefire.junit.JUnit3Provider.executeTestSet(JUnit3Provider.java:131)
	at org.apache.maven.surefire.junit.JUnit3Provider.invoke(JUnit3Provider.java:108)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)

Results :

Tests in error: 
  org.universAAL.ontology.test.ArtifactIT#testComposite FileNotFoundException C:...

--

From: _this issue has been automatically imported from our old issue tracker_

**Comment by amedranogil** [comment]
_Original author: @amedranogil (2014-05-08 12:51:21)_

Fixed, added requiered dependencies in Itests.

**Comment by amedranogil** [comment]
issue cloed on 2014-05-08 12:51:21
