### ISSUE TITLE
Use of JavaMail API in uAAL

### ISSUE THREAD

**Issue by amedranogil** [universAAL/platform#37]
_Originally Opened: Jörg Draeger (2015-01-06 11:19:10_)
_Originally Closed: 2015-01-15 11:54:51_

Hi,
I try to use JavaMail to send emails. This doesn' t work. It looks like the use of Session prevent the Matching....
 ------------------------------------------------------------------------------------------------------------------------
My code:
SCallee.java
import javax.mail.*;
import javax.mail.Message.RecipientType;
import javax.mail.internet.*;
import javax.activation.*;
....
 
private void sendEmail(){		
		System.out.println(&quot;Inside Method sendEmail()&quot;);
		//Recipient's email ID needs to be mentioned.
               String to = &quot;joerg.draeger@gmx.net&quot;;
	    // Sender's email ID needs to be mentioned
           String from = &quot;joergdraeger@yahoo.de&quot;;
	    // Assuming you are sending email from localhost
            String host = &quot;localhost&quot;;	
	    // Get system properties
	    Properties properties = System.getProperties();
	
	    // Setup mail server
	    properties.setProperty(&quot;smtp.mail.yahoo.com&quot;, host);
	    properties.setProperty(&quot;mail.user&quot;, &quot;joergdraeger&quot;);
	    properties.setProperty(&quot;mail.password&quot;, &quot;-----------&quot;);	
	    // Get the default Session object.
	    Session session = Session.getDefaultInstance(properties);	
	    try{
	    	System.out.println(&quot;try to send Email&quot;);
	    	 // Create a default MimeMessage object.
	         MimeMessage message = new MimeMessage(session);
	         // Set From: header field of the header.
	         message.setFrom(new InternetAddress(from));
	         // Set To: header field of the header.
	         message.addRecipient(Message.RecipientType.TO, new InternetAddress(to));
	         // Set Subject: header field
	         message.setSubject(&quot;Eine Email-Nachricht aus uAAL!&quot;);
	         // Now set the actual message
	         message.setText(&quot;Eine Email-Nachricht aus uAAL! BODY&quot;);
	         // Send message
	         Transport.send(message);
	         System.out.println(&quot;Sent service-request successfully to service-provider....&quot;);
	      }
	      catch (MessagingException mex) {
	        	mex.printStackTrace();
	      }
}
------------------------------------------------------------------------------------------------------------------------
Output:
...
ERROR: Bundle smart.sever [27] Error starting file:/C:/Users/Joerg/Development/workspace_smartLiving/rundir/demo.config/runner/bundles/smart.sever_3.1.0.SNAPSHOT.jar (org.osgi.framework.BundleException: Unresolved constraint in bundle smart.sever [27]: Unable to resolve 27.0: missing requirement [27.0] osgi.wiring.package; (osgi.wiring.package=javax.mail))
org.osgi.framework.BundleException: Unresolved constraint in bundle smart.sever [27]: Unable to resolve 27.0: missing requirement [27.0] osgi.wiring.package; (osgi.wiring.package=javax.mail)
 
...
w.container.osgi[org.universAAL.smart.client] : AccessControl-&gt;checkPermission(): Permission denied for Matchable: ContextEventPattern: urn:anonymous:_:c0a802649745a9ce:92c
	at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4002)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2045)
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1299)
	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:304)
	at java.lang.Thread.run(Unknown Source)
 
...
mw.container.osgi[org.universAAL.smart.client] : ServiceCaller-&gt;handleReply(): urn:uaal_space:6950fdaa-a906-4be8-a6c1-385a1f9a4277#3requester.smart.client received service response:
 
@prefix : &lt;http://ontology.universAAL.org/uAAL.owl#&gt; .
_:BN000000 a :ServiceResponse ;
  :callStatus :no_matching_service_found .
:no_matching_service_found a :CallStatus .
 
mw.container.osgi[org.universAAL.mw.bus.service.osgi] : ServiceStrategy-&gt;replyToLocalCaller(): There is no caller. To whom should I then reply? Ignoring it.
------------------------------------------------------------------------------------------------------------------------
Without the code beginning with &quot;Session session = Session...&quot; the matching works fine....
 
I've searched the uAAL-API for another way to send an email from inside of uAAL without success. Is there a way? Or what is the problem with the code above?
Thanks and Regards,
 Jörg

--

From: _this issue has been automatically imported from our old issue tracker_

**Comment by amedranogil** [comment]
_Original author: @Alfiva (2015-01-07 09:27:16)_

I saw this first in the forums, please look there: http://forge.universaal.org/gf/project/support/forum/?_forum_action=ForumMessageBrowse&amp;thread_id=150&amp;action=ForumBrowse&amp;forum_id=8

**Comment by amedranogil** [comment]
_Original author: @Alfiva (2015-01-15 11:54:51)_

Solved in the forum on 7th jan

**Comment by amedranogil** [comment]
issue cloed on 2015-01-15 11:54:51
