### ISSUE TITLE
R-API: Google Cloud Messaging for Android not found

### ISSUE THREAD

**Issue by amedranogil** [universAAL/platform#38]
_Originally Opened: Jörg Draeger (2015-01-12 12:13:14_)
_Originally Closed: 2015-05-26 17:21:29_

 Hi,

I added for the use of R-API the Google Cloud Messaing Service. 

As described in http://forge.universaal.org/wiki/rinterop:Remote_API in the list of repositories.

So I added 

&lt;repository&gt;

 &lt;id&gt;Thirdparty-repositories&lt;/id&gt;

 &lt;name&gt;Google Cloud Messaging for Android&lt;/name&gt;

 &lt;url&gt;http://depot.universaal.org/nexus/content/repositories/thirdparty&lt;/url&gt;

 &lt;releases&gt;

 &lt;enabled&gt;false&lt;/enabled&gt;

 &lt;/releases&gt;

&lt;/repository&gt;

to the pom.xml of my server. But the console still printed out:

ERROR: Bundle ri.api.manager [35] Error starting file:/C:/Users/Joerg/Development/workspace_smartLiving/rundir/demo.config/runner/bundles/ri.api.manager_3.1.3.SNAPSHOT.jar (org.osgi.framework.BundleException: Unresolved constraint in bundle ri.api.manager [35]: Unable to resolve 35.0: missing requirement [35.0] osgi.wiring.package; (osgi.wiring.package=com.google.android.gcm.server))
org.osgi.framework.BundleException: Unresolved constraint in bundle ri.api.manager [35]: Unable to resolve 35.0: missing requirement [35.0] osgi.wiring.package; (osgi.wiring.package=com.google.android.gcm.server)
 at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4002)
 at org.apache.felix.framework.Felix.startBundle(Felix.java:2045)
 at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1299)
 at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:304)
 at java.lang.Thread.run(Unknown Source)

What is the correct way to do it. Using eclipse, Win 7, PAX Runner, so no karaf til now.

After all has started there is an log wich is confusing me:

mw.container.osgi[org.universAAL.mw.brokers.control.osgi] : Activator-&gt;startBrokerClient(): Starting ControlBroker...
mw.container.osgi[org.universAAL.mw.connectors.communication.jgroups.osgi] : JGroupsCommunicationConnector-&gt;loadConfigurations(): updating JGroups Connector properties
mw.container.osgi[org.universAAL.mw.connectors.communication.jgroups.osgi] : JGroupsCommunicationConnector-&gt;JGroupsCommunicationConnector(): JGroups Connector properties updated
mw.container.osgi[org.universAAL.mw.brokers.control.osgi] : ControlBroker-&gt;init(): Fetching the AALSpaceModule...
mw.container.osgi[org.universAAL.mw.brokers.control.osgi] : ControlBroker-&gt;init(): No AALSpaceModule found
mw.container.osgi[org.universAAL.mw.brokers.control.osgi] : Activator-&gt;startBrokerClient(): Started ControlBroker!
DEBUG: WIRE: [52.0] osgi.wiring.package; (&amp;(osgi.wiring.package=com.google.gson)(version&gt;=2.2.0)(!(version&gt;=3.0.0))) -&gt; [10.0]

Does that mean, google service is running and working although the first error message was diplayed?

--

From: _this issue has been automatically imported from our old issue tracker_

**Comment by amedranogil** [comment]
_Original author: @Alfiva (2015-01-12 12:55:18)_

I would say the problem is with:

&lt;releases&gt;
 &lt;enabled&gt;false&lt;/enabled&gt;
&lt;/releases&gt;

Since that 3rd party repository is precisely for releases, it should not be disabled. That piece of XML is usually used for snapshot repositories. Try again without those lines.

Regarding the second part of the issue, it means bundle 52 is resolving com.google.gson. I don't know which is bundle 52, but it could be the R-API, not the GCM bundle, so that could be normal. We'll see when the first problem is solved.

**Comment by amedranogil** [comment]
_Original author: Jörg Draeger (2015-01-12 13:35:32)_

Hi Alvaro,

I deleted 

&lt;releases&gt;
 &lt;enabled&gt;false&lt;/enabled&gt;
&lt;/releases&gt;

without any effect. Still the error

org.osgi.framework.BundleException: Unresolved constraint in bundle ri.api.manager [35]: Unable to resolve 35.0: missing requirement [35.0] osgi.wiring.package; (osgi.wiring.package=com.google.android.gcm.server)
	at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4002)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2045)
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1299)
	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:304)
	at java.lang.Thread.run(Unknown Source)

**Comment by amedranogil** [comment]
_Original author: @Alfiva (2015-01-12 13:48:24)_

when you set the com.google.android.gcm/gcm.server bundle, do you put &quot;wrap:&quot; in front of it, not just &quot;mvn:&quot;?
Because this is just a simple jar, not an OSGi bundle, and perhaps it is not exporting its packages if you do not put &quot;wrap:&quot; before.

**Comment by amedranogil** [comment]
_Original author: Jörg Draeger (2015-01-12 14:15:40)_

I've tried it this way:
wrap:http://depot.universaal.org/nexus/content/repositories/thirdparty/com/google/android/gcm/gcm-server/1.0.2
on Level 9. On level 10 ri.api.manager starts.

Still the same.

**Comment by amedranogil** [comment]
_Original author: @Alfiva (2015-01-12 16:11:22)_

Sorry I missed one small sentence from your first post, but in any case the latter doesn't look very well either. Let's settle:

In your run config you must have the gcm jar with this:

wrap:mvn:com.google.android.gcm/gcm-server/1.0.2

And in your settings.xml file for maven, which should be in .m2 in your user folder, you must include the 3rd party repository, like this:

&lt;repository&gt;
 &lt;id&gt;Thirdparty-repositories&lt;/id&gt;
 &lt;name&gt;uAAL Thirdparty-repositories&lt;/name&gt;
 &lt;url&gt;http://depot.universaal.org/nexus/content/repositories/thirdparty&lt;/url&gt;
&lt;/repository&gt;

There is still a small chance that it doesnt work, but try this and let me know.

**Comment by amedranogil** [comment]
_Original author: Jörg Draeger (2015-01-13 10:35:32)_

That worked but brings up new errors :-(

RROR: Bundle ri.api.manager [35] Error starting file:/C:/Users/Joerg/Development/workspace_smartLiving/rundir/demo.config/runner/bundles/ri.api.manager_3.1.3.SNAPSHOT.jar (org.osgi.framework.BundleException: Unresolved constraint in bundle ri.api.manager [35]: Unable to resolve 35.0: missing requirement [35.0] osgi.wiring.package; (osgi.wiring.package=javax.servlet))
org.osgi.framework.BundleException: Unresolved constraint in bundle ri.api.manager [35]: Unable to resolve 35.0: missing requirement [35.0] osgi.wiring.package; (osgi.wiring.package=javax.servlet)
DEBUG: WIRE: [36.0] osgi.wiring.package; (&amp;(osgi.wiring.package=org.osgi.framework)(version&gt;=1.4.0)) -&gt; [0]
DEBUG: WIRE: [36.0] osgi.wiring.package; (&amp;(osgi.wiring.package=org.osgi.service.packageadmin)(version&gt;=1.2.0)) -&gt; [0]
DEBUG: WIRE: [36.0] osgi.wiring.package; (&amp;(osgi.wiring.package=org.osgi.service.startlevel)(version&gt;=1.1.0)) -&gt; [0]
DEBUG: WIRE: [36.0] osgi.wiring.package; (&amp;(osgi.wiring.package=org.osgi.service.url)(version&gt;=1.0.0)) -&gt; [0]
DEBUG: WIRE: [31.0] osgi.wiring.package; (&amp;(osgi.wiring.package=org.osgi.framework)(version&gt;=1.4.0)(!(version&gt;=2.0.0))) -&gt; [0]
DEBUG: WIRE: [31.0] osgi.wiring.package; (&amp;(osgi.wiring.package=org.osgi.service.log)(version&gt;=1.3.0)(!(version&gt;=2.0.0))) -&gt; [2.0]
	at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4002)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2045)
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1299)
	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:304)
	at java.lang.Thread.run(Unknown Source)

**Comment by amedranogil** [comment]
_Original author: @Alfiva (2015-01-13 11:24:21)_

From the required dependencies in the instructions in the wiki:

&quot;An implementation for OSGi HTTP Service. OPS4J Pax Web is usually included by default in the uAAL Karaf distros. Otherwise install feature &quot;http&quot;, or all the needed bundles independently&quot;

When using Karaf, installing the &quot;http&quot; feature also installs (I think) the javax.servlet. If not using Karaf you have to include that bundle manually (and all the other bundles needed for the Http OSGi service - e.g. Pax Web)

From the R API POM you can get the dependency ID:

    &lt;dependency&gt;
      &lt;groupId&gt;javax.servlet&lt;/groupId&gt;
      &lt;artifactId&gt;servlet-api&lt;/artifactId&gt;
      &lt;version&gt;2.5&lt;/version&gt;
      &lt;scope&gt;provided&lt;/scope&gt;
    &lt;/dependency&gt;

But take into account that it may conflict with whatever Web Service platform for OSGi you may use. Do you need support with installing a Web Service/Servlet container for OSGi?

**Comment by amedranogil** [comment]
_Original author: @Alfiva (2015-01-13 11:26:18)_

Small update: when installing Karaf &quot;http&quot; feature the javax.servlet package is provided by bundle &quot;geronimo-servlet_2.5_spec&quot;

**Comment by amedranogil** [comment]
_Original author: Jörg Draeger (2015-01-13 11:39:14)_

I'm in contact with Helmi and he want's to help me today. Otherwise I will let you know.

Meanwhile I will try by myself with your last hints ;-)

**Comment by amedranogil** [comment]
issue cloed on 2015-05-26 17:21:29
