### ISSUE TITLE
Syntax of creating Turtle

### ISSUE THREAD

**Issue by amedranogil** [universAAL/platform#39]
_Originally Opened: Jörg Draeger (2015-01-20 11:25:36_)
_Originally Closed: 2015-01-30 14:18:29_

Hi,

I can register to a uAAL-Server using the remote-api. Now I want to call a Service Request. 

I compose a turtle message and send it via POST to the server. But it looks like it is not a correct serialized service request. 

[Error 500 org.universAAL.ri.api.manager.exceptions.APIImplException: Unable to deserialize request]

How are the syntax and rules to do so?

My Service Request Java-Client to uAAL-Server is:

responder.smart.server received service call:

@prefix ns: &lt;http://sample.universAAL.org/Server.owl#&gt; .
@prefix : &lt;http://www.daml.org/services/owl-s/1.1/Process.owl#&gt; .
_:BN000000 a :Perform ;
  :hasDataFrom (
    [
      a :InputBinding ;
      :toParam ns:goods ;
      :valueData &quot;&quot;&quot;
        @prefix : &lt;http://ontology.universAAL.org/SmartOntology#&gt; .
        &lt;breads&gt; a :Goods ,
            :Provisions .
        &quot;&quot;&quot;^^&lt;http://www.w3.org/1999/02/22-rdf-syntax-ns#XMLLiteral&gt;
    ]
  ) ;
  :process ns:orderGoodsProcess .
ns:goods a :Input .

Can I derive the Turtle message form this call?

BR, Jörg

--

From: _this issue has been automatically imported from our old issue tracker_

**Comment by amedranogil** [comment]
_Original author: @Alfiva (2015-01-20 11:38:23)_

No, that is actually a ServiceCall, not a ServiceRequest.
ServiceRequests are the &quot;items&quot; sent from Service Callers to the the bus, then the bus does the matchmaking and creates a ServiceCall that sends to the Service Callee. I know it is a mess, but that's how it goes.
To get a serialization you can use in R API, serialize the ServiceRequest: just use the MessagContentSerializer on your ServiceRequest object before you .call() it with the caller.

Also, I don't remember exactly right now, but maybe the blank node as the root of the serialization may be problematic. Try just as I said first, with ServiceRequest, and if you still have problems, check if the root (the first resource) is _:BN000000. If so, try giving a explicit custom URI to your Request.

**Comment by amedranogil** [comment]
_Original author: Jörg Draeger (2015-01-20 14:26:18)_

Thanks for very quick answer.

I serialized the Service Request with MessageContentSerializer. Result is below.
I will try this as Turtle Message.

@prefix ns: &lt;http://ontology.universaal.org/PhThing.owl#&gt; .
@prefix owl: &lt;http://www.w3.org/2002/07/owl#&gt; .
@prefix ns1: &lt;http://ontology.universAAL.org/SmartOntology#&gt; .
@prefix : &lt;http://ontology.universAAL.org/uAAL.owl#&gt; .
_:BN000000 a :ServiceRequest ;
  :requestedService [
    a ns:DeviceService ;
    :instanceLevelRestrictions (
      [
        owl:hasValue &lt;breads&gt; ;
        a owl:Restriction ;
        owl:onProperty ns:controls
      ]
    ) ;
    :numberOfValueRestrictions &quot;1&quot;^^&lt;http://www.w3.org/2001/XMLSchema#int&gt;
  ] .
&lt;breads&gt; a ns1:Goods ,
    ns1:Provisions .


I will come up with the final result. Thanks again.

**Comment by amedranogil** [comment]
_Original author: Jörg Draeger (2015-01-20 15:28:16)_

With the Turtle Message above there is an exception in uAAL:

org.universAAL.middleware.service.ServiceRequest.addScope(Ljava/lang/String;)Z 
Caused by:
java.lang.NoSuchMethodError: org.universAAL.middleware.service.ServiceRequest.addScope(Ljava/lang/String;)Z
	at org.universAAL.ri.api.manager.RemoteAPIImpl.callS(RemoteAPIImpl.java:137)
	at org.universAAL.ri.api.manager.server.RemoteServlet.doPost(RemoteServlet.java:125)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
	at org.apache.felix.http.base.internal.handler.ServletHandler.doHandle(ServletHandler.java:91)
	at org.apache.felix.http.base.internal.handler.ServletHandler.handle(ServletHandler.java:77)
	at org.apache.felix.http.base.internal.dispatch.ServletPipeline.handle(ServletPipeline.java:42)
	at org.apache.felix.http.base.internal.dispatch.InvocationFilterChain.doFilter(InvocationFilterChain.java:49)
	at org.apache.felix.http.base.internal.dispatch.HttpFilterChain.doFilter(HttpFilterChain.java:33)
	at org.apache.felix.http.base.internal.dispatch.FilterPipeline.dispatch(FilterPipeline.java:48)
	at org.apache.felix.http.base.internal.dispatch.Dispatcher.dispatch(Dispatcher.java:39)
	at org.apache.felix.http.base.internal.DispatcherServlet.service(DispatcherServlet.java:55)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:390)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:326)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:536)
	at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:915)
	at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:539)
	at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:405)
	at org.mortbay.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:409)
	at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)


Looks like there is something wrong with the message. Any hints?

**Comment by amedranogil** [comment]
_Original author: Jörg Draeger (2015-01-20 15:31:23)_

This is the URL encoded

http://localhost:8080/universaal?method=CALLS&amp;param=%40prefix%20ns%3A%20%3Chttp%3A%2F%2Fontology.universaal.org%2FPhThing.owl%23%3E%20.%40prefix%20owl%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2002%2F07%2Fowl%23%3E%20.%40prefix%20ns1%3A%20%3Chttp%3A%2F%2Fontology.universAAL.org%2FSmartOntology%23%3E%20.%40prefix%20%3A%20%3Chttp%3A%2F%2Fontology.universAAL.org%2FuAAL.owl%23%3E%20._%3ABN000000%20a%20%3AServiceRequest%20%3B%3ArequestedService%20%5Ba%20ns%3ADeviceService%20%3B%3AinstanceLevelRestrictions%20%28%5Bowl%3AhasValue%20%3Cbreads%3E%20%3Ba%20owl%3ARestriction%20%3Bowl%3AonProperty%20ns%3Acontrols%5D%29%20%3B%3AnumberOfValueRestrictions%221%22%5E%5E%3Chttp%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23int%3E%5D%20.%3Cbreads%3E%20a%20ns1%3AGoods%20%2Cns1%3AProvisions%20.

and clear

@prefix ns: &lt;http://ontology.universaal.org/PhThing.owl#&gt; .
@prefix owl: &lt;http://www.w3.org/2002/07/owl#&gt; .
@prefix ns1: &lt;http://ontology.universAAL.org/SmartOntology#&gt; .
@prefix : &lt;http://ontology.universAAL.org/uAAL.owl#&gt; .
_:BN000000 a :ServiceRequest ;
:requestedService [
a ns:DeviceService ;
:instanceLevelRestrictions (
[
owl:hasValue &lt;breads&gt; ;
a owl:Restriction ;
owl:onProperty ns:controls
]
) ;
:numberOfValueRestrictions
&quot;1&quot;^^&lt;http://www.w3.org/2001/XMLSchema#int&gt;] .
&lt;breads&gt; a ns1:Goods ,
ns1:Provisions .


respectivly 

@prefix ns: &lt;http://ontology.universaal.org/PhThing.owl#&gt; .@prefix owl: &lt;http://www.w3.org/2002/07/owl#&gt; .@prefix ns1: &lt;http://ontology.universAAL.org/SmartOntology#&gt; .@prefix : &lt;http://ontology.universAAL.org/uAAL.owl#&gt; ._:BN000000 a :ServiceRequest ;:requestedService [a ns:DeviceService ;:instanceLevelRestrictions ([owl:hasValue &lt;breads&gt; ;a owl:Restriction ;owl:onProperty ns:controls]) ;:numberOfValueRestrictions&quot;1&quot;^^&lt;http://www.w3.org/2001/XMLSchema#int&gt;] .&lt;breads&gt; a ns1:Goods ,ns1:Provisions .

**Comment by amedranogil** [comment]
_Original author: @Alfiva (2015-01-20 17:48:02)_

no, not a problem with the message. Looks like a version issue with the MW, like it is not multitenant. Which MW version are you using?

**Comment by amedranogil** [comment]
_Original author: Jörg Draeger (2015-01-21 09:38:54)_

MW Version 3.1.0

**Comment by amedranogil** [comment]
_Original author: @Alfiva (2015-01-21 09:52:21)_

That's it. Multitenancy was introduced in MW 3.2.0

**Comment by amedranogil** [comment]
_Original author: Jörg Draeger (2015-01-21 12:08:41)_

A long way! But finally the first tests looks very promissing! It seems to work.
Thanks.

**Comment by amedranogil** [comment]
issue cloed on 2015-01-30 14:18:29
